### ISSUE TITLE
Doing oauth against freshbooks is far from obvious

### ISSUE THREAD

**Issue by trcull** [elucid/ruby-freshbooks#3]
I know oauth is outside the purview of this gem, but I do think it would be useful to link to some instructions how to do it.  I found when trying to do it that the oauth gem and Freshbook's way of doing oauth don't play well together, mainly because Freshbooks requires PLAINTEXT.

I've written up the gory details here:
http://cms.pollen.io/2012/10/doing-oauth-authentication-in-ruby-with-freshbooks/

of course, I'm happy for you to link straight to it in the README.  But I figured I'd be a little too full of myself if I just went ahead and did that and sent a pull request.

**Comment by elucid** [comment]
Hey there, thanks for the heads-up. I think you're right--there should probably be some suggestion as to how to get this going. When I was developing ruby-freshbooks I had written a little script to obtain oauth tokens and I probably should have included it in the repo, if only as an example.

While your post is probably useful for someone struggling with this issue, I am reluctant to link to it because it spends much more time chronicling how your solution was developed, rather than the result and how to use it. I would rather have something that is clear and straight-forward that someone can use without having to pick through and understand your process.
